### ISSUE TITLE
Make the Readme more descriptive

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#1]
- [x] The readme should contain more description about the problem with links to the existing solution on Github.

- [x] Since it is a python learning projet, it should contain some resources links and guides to get started with python.

**Comment by jd7h** [comment]
I can do the second point of the checklist. :)

**Comment by Alyssa-Cooper** [comment]
If you need more resources to help beginners with Python I would be more than happy to add some. I have a few good links

**Comment by jd7h** [comment]
I guess my tiny list could act as a starting point, but there's certainly room for more!

**Comment by prateekiiest** [comment]
Yeah sure @Alyssa-Cooper

**Comment by iyanuashiri** [comment]
I want to work on the README, can I continue?

**Comment by prateekiiest** [comment]
Sure @iyanuashiri
