### ISSUE TITLE
Running tic-tac-toe/code.py first gave the error `NameError: global name 'random' is not defined`. 

### ISSUE THREAD

**Issue by susg** [prateekiiest/Code-Sleep-Python#106]
Maintainer: @prateekiiest

## DESCRIPTION

Please provide a short, clear description of the problem

## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem

## EXPECTED OUTCOME

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by susg** [comment]
This is a copy of this [issue](https://github.com/prateekiiest/Code-Sleep-Python/issues/107)

**Comment by prateekiiest** [comment]
sure, do you wanna work on it?

I guess you just have to import the random function

**Comment by FinMacDov** [comment]
Hey seen this project as part of the mozilla Global sprint. I can I try fix this bug?

**Comment by prateekiiest** [comment]
yeah, sure right away :+1:

**Comment by adityac8** [comment]
Hey @prateekiiest I tried fixing the bug but it shows that the function `place` is not defined.

**Comment by FinMacDov** [comment]
Sorry just seen this now. I fixed in the missing place function in my first commit for issues #106. Issues #106 and #107 should be resolved.

**Comment by FinMacDov** [comment]
I think this issue can be closed as tic-tac-toe now runs. I fixed it during the global sprint.
