### ISSUE TITLE
Getting `NameError: global name 'place' is not defined` in tic-tac-toe

### ISSUE THREAD

**Issue by susg** [prateekiiest/Code-Sleep-Python#107]
First tic-tac-toe/code.py gave the error:
`NameError: global name 'random' is not defined`

Then I added `import random` to the code. Now it gives the error:
`NameError: global name 'place' is not defined`

Numpy version = 1.14.0

**Comment by prateekiiest** [comment]
OK, I think there has been some error which the tests did not detect.

Could you add this

**Comment by susg** [comment]
what is the`place()` fn supposed to do ?

**Comment by prateekiiest** [comment]
`place()` was used to place the `X` or `O` in corresponding position in the board.
board is the 2d array

**Comment by prateekiiest** [comment]
I actually worked on this code in my jupyter notebook and somehow didn't upload that part.
I think that part needs to be rewritten keeping other portions intact.

**Comment by adityac8** [comment]
Hey @prateekiiest I would like to work on this one.

**Comment by prateekiiest** [comment]
sure, you can fix both those issues in the PR you opened. Just mention the proper issue numbers

**Comment by prateekiiest** [comment]
@adityac8 you can see the PR here https://github.com/prateekiiest/Code-Sleep-Python/pull/114

**Comment by prateekiiest** [comment]
you can help him with fixing the pep8 issues you see there
