### ISSUE TITLE
Website Status Check Project add more status codes

### ISSUE THREAD

**Issue by molex** [prateekiiest/Code-Sleep-Python#110]
Maintainer: [@prateekiiest](https://github.com/prateekiiest)

## DESCRIPTION

TODO of adding more status codes

## STEPS TO REPRODUCE

no repro, just adding functionality

## EXPECTED OUTCOME

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

Add more status codes using list from Mozilla: [status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

**Comment by molex** [comment]
I would like to have this assigned to me for the MozSprint.

**Comment by prateekiiest** [comment]
Sure @molex . I am assigning this to you.
Thanks for taking up :100:

**Comment by molex** [comment]
Thanks for allowing me an opportunity to help out. I enjoyed it.
