### ISSUE TITLE
Chatbot in Python - Implement text to speech output and speech to text input

### ISSUE THREAD

**Issue by adeen-s** [prateekiiest/Code-Sleep-Python#111]
Maintainer: [@prateekiiest](https://github.com/prateekiiest)

## DESCRIPTION
Start the work on Chatbot in Python by implementing the basic I/O functionality first. 

## EXPECTED OUTCOME
Get user input using voice and and convert it to a string. Use the same string for to provide a voice output to the user. Further functionality of the chatbot such as processing the input can be implemented later.

### ADDITIONAL NOTES
Add this issue to the Chatbot Project board and assign this issue to me please :heart_eyes: .

**Comment by prateekiiest** [comment]
Would love to see that come alive.
@adeen-s keep it going

**Comment by Savidude** [comment]
Hi, I have been working on a similar application for a while which I think might be relevant to this, and you might find interesting.

The TL;DR version of the project is that it is a tool along with a programming language that can be used to develop chatbots. Although it only works with text at this point, text to speech, and speech to text can be easily implemented. The core of this project is entirely implemented using Python.

Please take a look if you are interested :)
[Project repository](https://github.com/Savidude/cuneiform)
[Project documentation](https://savidude.github.io/cuneiform-docs/)
[Video explaining the project](https://youtu.be/DH3sNpNH8Ow)
