### ISSUE TITLE
Organise Documentation 

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#113]
Instead of maintaining the documentation of all the projects in the README, it would be better if we can include all such documentation in a proper README under corresponding project folders.

So each project folder will now contain:

- project code
- project requirements.txt
- project readme

**Comment by Abwas** [comment]
So how can i contribute to organizing the documentation?

**Comment by prateekiiest** [comment]
you can work on shifting the readme documentation for each project to its corresponding folder readme
