### ISSUE TITLE
Add regression models

### ISSUE THREAD

**Issue by siddas27** [prateekiiest/Code-Sleep-Python#121]
Maintainer: [@prateekiiest](https://github.com/prateekiiest)

## DESCRIPTION

Add regression models to the repo just like classiification.

## EXPECTED OUTCOME

1. create a 'regression' folder inside Code-Sleep-Python.
2. add a requirement.txt file which will include all required pakages.
3. Add .py file or jupyter notebook of various regression models.

Please assign this to me.

**Comment by siddas27** [comment]
I have made a pull request completing all issues mentioned. Please merge it under Mozsprint

**Comment by prateekiiest** [comment]
I am closing this. 😄 . Open if any updates
