### ISSUE TITLE
Update requirements.txt 

### ISSUE THREAD

**Issue by FinMacDov** [prateekiiest/Code-Sleep-Python#123]
Maintainer: [@prateekiiest](https://github.com/prateekiiest)

## A number of the directories missing requirements.txt 

Please provide a short, clear description of the problem

## Add the requirements.txt with the packages need for the project. 

Please list the steps to reproduce the above problem

## Add textile listing the required packages for a code contained in the directory.  

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by siddas27** [comment]
I would like to do that.

**Comment by Cereal84** [comment]
I've submited my pull request  (#142 ) for this issue.
