### ISSUE TITLE
Snake game code not in pep8 style

### ISSUE THREAD

**Issue by FinMacDov** [prateekiiest/Code-Sleep-Python#124]
Maintainer: [@prateekiiest](https://github.com/prateekiiest)

## DESCRIPTION

Snake game code not in pep8 style

## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem

## EXPECTED OUTCOME

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by prateekiiest** [comment]
I am closing this. 😄 . Open if any updates
