### ISSUE TITLE
Code-Slee-Python Classification Folder code.py not compiling 

### ISSUE THREAD

**Issue by RavinduHasithanjana** [prateekiiest/Code-Sleep-Python#125]
Maintainer: [@prateekiiest](https://github.com/prateekiiest)

## DESCRIPTION

I installed the dependencies of for the code.py but when running an issue occurs 

<img width="913" alt="screen shot 2018-05-11 at 2 59 47 pm" src="https://user-images.githubusercontent.com/17488349/39917767-314fbe46-552c-11e8-9bf3-08614db96032.png">

The Following issue is shown above in the screenshot, so please help to fix in-order to provide the work 

## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem

## EXPECTED OUTCOME

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by prateekiiest** [comment]
@molex or @RavinduHasithanjana 

anyone of you can work on it.

**Comment by prateekiiest** [comment]
Would be great if you can find the bug

**Comment by molex** [comment]
There are a number of issues in this project so far. Can anyone give me any insight into what the variable numeric_data is supposed to be representing from the dataset?

**Comment by molex** [comment]
Never mind, I believe I have it resolved now.
