### ISSUE TITLE
Broken image link 

### ISSUE THREAD

**Issue by vchrombie** [prateekiiest/Code-Sleep-Python#139]
**Describe the bug**
Broken image link in [floating text](https://github.com/prateekiiest/Code-Sleep-Python/tree/master/Code-Sleep-Python/floating_text) README

**To Reproduce**
https://github.com/prateekiiest/Code-Sleep-Python/blob/master/floating_text.gif

**Expected behavior**
GIF to be shown.

**Comment by jayvasantjv** [comment]
To Reproduce link is broken!
