### ISSUE TITLE
Add new clustering python project

### ISSUE THREAD

**Issue by PongsakornAj** [prateekiiest/Code-Sleep-Python#164]
For this repository already have a classification algorithm, but don't have any clustering algorithm.

I already create clustering algorithm in python language. It is DBSCAN algorithm and I write this algorithm by scratch. In this codes have a basic code ,function and visualization algorithm step by step for beginner.

I hope you will add my python project to this repository for other python lover.

**Comment by Mansi145** [comment]
Is this issue up for assigning? I would like to work on this.
