### ISSUE TITLE
Visualization of Sieve algorithm

### ISSUE THREAD

**Issue by hs2361** [prateekiiest/Code-Sleep-Python#180]
It would be great if there was a visual representation of the popular Sieve of Eratosthenes algorithm for primes. This could be made generalized, for any natural number 'n'. This would serve as a good tool for understanding the algorithm in a better way.

**Comment by hs2361** [comment]
Can I be assigned to this issue @prateekiiest ?

**Comment by prateekiiest** [comment]
Sure @hs2361

**Comment by prateekiiest** [comment]
Closed in favour of #181
