### ISSUE TITLE
Render Emojis in the HTML Page

### ISSUE THREAD

**Issue by vkoul** [prateekiiest/Code-Sleep-Python#182]
Hi Prateek, 

Thanks for maintaining this wonderful repository. 
Checked the associated Github page. Just a small suggestion, add the below to your _config.yml file
```
plugins:
  - jemoji
```
This will render the emojis on the webpage. It will make it similar to the repository README.

[Example Webpage with emojis](https://vkoul.github.io/Data-Science-Resources/)

**Comment by prateekiiest** [comment]
Thanks @vkoul for your suggestions on this.
And thanks for stumbling upon this repository. :)

Look forward if you want to contribute something here

**Comment by prateekiiest** [comment]
Closing via #183
