### ISSUE TITLE
Project: OpenCV Sudoku Solver using OCR

### ISSUE THREAD

**Issue by chhipashubham970** [prateekiiest/Code-Sleep-Python#189]
I want to add a project which solves sudoku using OpenCV and OCR. 
If you like this idea please assign me this project.

**Comment by prateekiiest** [comment]
sure go ahead @chhipashubham970

**Comment by aaryaab** [comment]
Hey, I want to add a project, which makes a person invisible. It is based on OpenCV. If you like the idea, please assign me this project.
