### ISSUE TITLE
Add dependencies in README

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#19]
Since some of the codes are already being implemented , it would be better to add the packages being used in each such code.

Create a new subheading called dependencies. Under that list the items.

For example if your code uses numpy then add numpy under dependencies. Or if scipy, then list it there.
Also do so for the existing codes since it is not mentioned.

**Comment by de1ux** [comment]
How does individual requirements.txt's sound?

**Comment by prateekiiest** [comment]
Yeah thats ok too :)
