### ISSUE TITLE
List all the projects in the README

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#20]
All the projects are not listed here
https://github.com/prateekiiest/Code-Sleep-Python#projects

**Comment by BinSquare** [comment]
I'll add in the missing projects to readme.

**Comment by prateekiiest** [comment]
Thanks @BinSquare

**Comment by BinSquare** [comment]
Pull request made here : [https://github.com/prateekiiest/Code-Sleep-Python/pull/26](url)

**Comment by prateekiiest** [comment]
New projects being added

List them

**Comment by skapunker** [comment]
Pull request to list new projects: https://github.com/prateekiiest/Code-Sleep-Python/pull/53
