### ISSUE TITLE
ANNOUNCEMENT !!! Add your name in the Contributors List

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#21]
Hey all 

Thanks for your valuable contributions ❤️ .
Hope you had a great **Hacktoberfest**.

And thus to make your contribution public to everyone, you need to add your name in the CONTRIBUTORS.md

See example

| Github username      | Pull Request           | Status  |
| ------------- |:-------------:| -----:|
|   [prateekiiest](https::/github.com/prateekiiest) | embeded pull request link  | Open/Closed/Merged  |

#### Add embedded link for name and PR
Similarly add away by adding such `|`

**Comment by prateekiiest** [comment]
# Contributions list for KWOC

**Comment by vchrombie** [comment]
Table for Contributors to KWoC is not done.
Can I make an another table for that?

**Comment by prateekiiest** [comment]
Yes you can make another table.
But I guess @BrianMwangi21 has already registered in that table

**Comment by prateekiiest** [comment]
no @stalebot
