### ISSUE TITLE
Add simple games 

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#41]
I have worked with some and will be uploading soon.
In the mean time try out making a new game (simple one) if possible try to give make one application or applet using jython

**Comment by shourya28** [comment]
Could I work on making a new simple snake and ladders game and a Ludo game coded in python?

**Comment by FinMacDov** [comment]
Could I work on making a new simple game? Thinking of making a connect four game in python.

**Comment by prateekiiest** [comment]
sure @FinMacDov

**Comment by shanaka95** [comment]
I have some Image processing projects.Can I add those projects?
