### ISSUE TITLE
ANNOUNCEMENT !! Joining SLACK

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#67]
People who have currently forked the repo, please join the slack through the link given in the readme.

**Comment by kkbit96** [comment]
Hi prateekiiest..
It seems that you have not imported any libraries in the birdsmigration project.
Also I am unable to join the the slack that you have announced.
Looking forward to hear from you...

**Comment by prateekiiest** [comment]
Hi @kkbit96 

I know that I haven't written any libraries in that code, so I was gonna update them but unfortunately forgot later about.

I hope to update that soon, but I am quite busy this week.

Regarding slack, did you check the joining link that I gave in the readme?

**Comment by kkbit96** [comment]
Yeah got it..
I have done my beginner's course in Machine learning but novice to its programming concepts.
I am looking forward to participate in KWoC. Also I am planning to go for GSoC this time.
where should i start with? Any suggestions...?

**Comment by prateekiiest** [comment]
Its great you did the ML course and its really great that you wish to go for the next  GSoC.
This KWOC event will prepare you for GSoC since it is similar to that. You need to work on existing issues and find the bug in the code and contribute to the organisation. That's all about GSoC. 

Find previous year organisations in the GSoC page and go through their project ideas. Work with those organisations that match your interests and also the programming language suits you.

**Comment by vchrombie** [comment]
A badge "chat on Slack" in the README.md would be great. 
Can I add that?

**Comment by prateekiiest** [comment]
sure @vchrombie
