### ISSUE TITLE
PyAPI: A new project which focuses on REST API.

### ISSUE THREAD

**Issue by apb7** [prateekiiest/Code-Sleep-Python#72]
The project which will use various public REST APIs for different purposes: Command Line Interface, Web Applications etc.
For example, A CLI using Github API which pulls all the notifications from your Github's dashboard.
This project can be developed further.

**Comment by prateekiiest** [comment]
That's a very good idea @apb7 .
Also it can be extended to see one's starred repos and repo contributions.

Surely you can start working on it. 👍

**Comment by apb7** [comment]
Yes! This can be done easily.

**Comment by apb7** [comment]
Hey @prateekiiest ! Sorry for catching up so late on this issue. 
What should be the directory structure for this issue? Shall I use `py_api` folder for the scripts which work around with APIs ?
