### ISSUE TITLE
Use Tkinter for  making a GUI implementation of the Tic-Tac-Toe

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#73]
### KWOC Project idea

**Comment by aditodkar** [comment]
Hi I would like to work on this can you assign it to me. I am familiar with python and tkinter.

**Comment by apb7** [comment]
@prateekiiest I already have this up and running. With a few tweaks, it can be adjusted to the current algorithm in the repository. [Tic-Tac-Toe](www.github.com/apb7/tic-tac-toe)

**Comment by aditodkar** [comment]
Are you working on this. Ok no problem

**Comment by apb7** [comment]
@aditodkar We can surely work on it together :)

**Comment by prateekiiest** [comment]
You can both work on it

**Comment by apb7** [comment]
@prateekiiest: I intend on changing the complete code for `code.py` in `tic-tac-toe`. The current code does not work as a few functions are not defined. We can work without the `numpy` module too.
