### ISSUE TITLE
Slack and Coding

### ISSUE THREAD

**Issue by BrianMwangi21** [prateekiiest/Code-Sleep-Python#75]
Hi, I joined the Slack workspace - but it's empty.
I know the project is to start coding on 1st Dec but we can still be active. Join Slack, get ideas, help each other.

I'm new on github and I would like to really contribute to this. Thanks

**Comment by prateekiiest** [comment]
join the general channel

**Comment by BrianMwangi21** [comment]
Ah! Found you
