### ISSUE TITLE
Add more problems in python

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/Code-Sleep-Python#8]
Like the implemented problems add more problems in python.
Simple problems like implementation of sorting, searching should not be submitted.
Consider more mathematical problems.

Some problems which can be implemented are : 

- [ ] Finding local maxima and local minima in a data
- [X] Finding number of primes within a range
- [ ] Simple classification algorithms with visualizations

Try to add something good like simple games also can do (python necessarily)

**Comment by st900278** [comment]
I can do "Finding number of primes within a range"

**Comment by bhansa** [comment]
I would like to add more on the prime numbers @prateekiiest

**Comment by prateekiiest** [comment]
You can create a new folder yourself by sending a PR . 😃 
See this issue #6

**Comment by aditya1904** [comment]
I would like to add different Encryption techniques @prateekiiest.

**Comment by prateekiiest** [comment]
Sure @aditya1904

**Comment by sks4903440** [comment]
I'd like to add terminal based Rock Paper Scissors game.

**Comment by fiott248** [comment]
i would like to add a python script that check if website is online or being redirected

**Comment by prateekiiest** [comment]
@Alyssa-Cooper @st900278 @bhansa @aditya1904 @sks4903440 @fiott248 

see here #21  to add your names.

Thanks for your contributions

**Comment by prateekiiest** [comment]
See  Issue #41
