### ISSUE TITLE
Indentation error in line 210 of inceptionTTT.py in Inception tic tac toe folder

### ISSUE THREAD

**Issue by rahuldcoder** [prateekiiest/Code-Sleep-Python#90]
Maintainer: @prateekiiest

## DESCRIPTION

There is an indentation error in line 210  

## STEPS TO REPRODUCE

Run inceptionTTT.py present in Inception tic tac toe folder

## EXPECTED OUTCOME

Should run the program

## ACTUAL OUTCOME

IndentationError: unexpected indent

### Proposed Solution [optional]

Just make the indentation proper

**Comment by prateekiiest** [comment]
Thanks @rahuldcoder for pointing that bug out.
Could you please update that ?

**Comment by rahuldcoder** [comment]
Ya sure

**Comment by prateekiiest** [comment]
I am closing this. 😄 . Open if any updates

**Comment by molex** [comment]
There are a ton of errors in this one, I am taking it (since I have already been working on it)
