### ISSUE TITLE
Identation error in line #72 off the social_network project

### ISSUE THREAD

**Issue by rahuldcoder** [prateekiiest/Code-Sleep-Python#91]
Maintainer: @prateekiiest

## DESCRIPTION

There is an identation error in #72 of social network project.

## STEPS TO REPRODUCE

Simply run code.py

**Comment by prateekiiest** [comment]
could you please work on this @rahuldcoder ?

**Comment by rahuldcoder** [comment]
Ya sure

**Comment by rahuldcoder** [comment]
Sorry for delayed response I have completed removed the error but now I have another error 
Traceback (most recent call last):
  File "code.py", line 2, in <module>
    df = pd.read_stata(data_filepath + "individual_characteristics.dta")
NameError: name 'data_filepath' is not defined

**Comment by prateekiiest** [comment]
'data_filepath' is your local directory filepath

**Comment by prateekiiest** [comment]
I will see to it when I get time

**Comment by prateekiiest** [comment]
No one worked on this so far.
Actually there has been some indentation error problems along with pep8 issues that needs to be fixed under the project module.

Should I assign you this?

**Comment by walkingzen** [comment]
Sure. I will make a try.
