### ISSUE TITLE
SyntaxError in Prime

### ISSUE THREAD

**Issue by nupurgunwant** [prateekiiest/Code-Sleep-Python#94]
Maintainer: @prateekiiest

## DESCRIPTION

Syntax Error in Prime

## STEPS TO REPRODUCE

'python code.py'

## EXPECTED OUTCOME

Enter the range of the number from:

## ACTUAL OUTCOME

File "code.py", line 105
    print("Brute force:", prime(range_from, range_to), end='\n\n')
                                                          ^
SyntaxError: invalid syntax

### Proposed Solution [optional]

use 'python3 code.py'

**Comment by adeen-s** [comment]
I don't think that this is a bug. Most Linux distributions ship with python 3.x as the default now. Python 2.x will only be supported for 2 more years i.e. till 2020
